import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import usePersistReducer from '@/hooks/usePersistReducer';

export default function Home() {
  const initialState = {
    value: 'foobar'
  }
  function reducer(state, action) {
    switch (action.type) {
      case 'setValue': {
        console.log('setValue: ', action.value);
        return {
          ...state,
          value: action.value
        }
      }
      default:
        console.log('unrecognized action type:', action.type);
        return state;
    }
  }
  const [state, dispatch] = usePersistReducer('value', reducer, initialState);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Localstorage saved value:
        <span>
          {state.value}
        </span>
        <input onChange={e => dispatch({ type: 'setValue', value: e.target.value})} />
      </main>
    </>
  )
}
